---
- name: create | all
  hosts: all
  remote_user: root
  become: true
  gather_facts: false
  ignore_unreachable: true
  
  tasks:
    - name: Show message
      ansible.builtin.debug:
        msg: "create task executed."